### ISSUE TITLE
setChild() function

### ISSUE THREAD

**Issue by ricmail85** [TMRh20/RF24Mesh#49]
Dear TMRh20,

I was looking at your new setChild function. Is it correct? Because in RF24Mesh.cpp, I don't see any difference if the "allow" parameter is true or false... I.e. it seems that the FLAG_NO_POLL is not triggered by the "allow" parameter...

I'm doing it wrong?

**Comment by TMRh20** [comment]
Need to ensure rf24network version is 1.0.2 in lib manager

Sent from my iPod

On 2015-11-29, at 1:37 AM, ricmail85 <notifications@github.com> wrote:

Dear TMRh20,

I was looking at your new setChild function. Is it correct? Because in
RF24Mesh.cpp, I don't see any difference if the "allow" parameter is true
or false... I.e. it seems that the FLAG_NO_POLL is not triggered by the
"allow" parameter...

I'm doing it wrong?

—
Reply to this email directly or view it on GitHub
<https://github.com/TMRh20/RF24Mesh/issues/49>.

**Comment by ricmail85** [comment]
Hi, 
yes I updated both libs... But if you see the setChild func, the input parameter "allow" is never used... Is it right? How the func would know if I want to enable or disable children for this node?

**Comment by TMRh20** [comment]
¬_¬  ... Well it worked perfectly well half of the time.

Thanks for pointing this out!

**Comment by ricmail85** [comment]
Thank you for your fast fix!
