### ISSUE TITLE
Radio power level

### ISSUE THREAD

**Issue by wiredman** [TMRh20/RF24Mesh#52]
during the mesh search I think power should start out low, and increase the level as needed upon fail.

**Comment by TMRh20** [comment]
I actually experimented with this to some extent, but had mixed results that I was not happy with at the time. 

The method used was probably overly simplistic, in that it just started out low when polling, and was raised until address renewal was successful. The problem with this is that nodes tended to join the mesh sometimes with a 'crappy' connection, and were more likely to attach as a child node, rather than directly to the master, depending on layout/topology.

I think there may still be benefit in exploring these concepts further, but finding efficient, simple and low-resource methods of doing these types of things seems to require a fair bit of experimentation + trial and error, which is very time consuming. Any input, code examples and additional experimentation would be helpful.
