### ISSUE TITLE
Not master node

### ISSUE THREAD

**Issue by gepd** [TMRh20/RF24Mesh#59]
Today someone told me about the feature in zigbee, to do a mesh without need of a master node. Would be that possible with the nrf24 and your library/ies?

Seems easily to know the advantages, but what could be the disadvantages to a mesh with this characteristics with this modules?

**Comment by TMRh20** [comment]
Would be possible, but it depends. In a small area, you are restricted to a tree topology per the manufacturer.

If we are talking very large distances, then RF overlap is not a problem, and the possibilities are endless as long as the physical structure of the network is managed properly. This type of network would likely be very slow compared to RF24Network, due to the need for discovery etc.
