### ISSUE TITLE
Authentication?

### ISSUE THREAD

**Issue by kluzzebass** [TMRh20/RF24Mesh#81]
Greetings!

Have you given any thought to authenticating nodes before they're allowed to enter into a mesh network?

I'm not primarily thinking about the security aspect of this, but rather about how to avoid nodes hopping between two adjacent mesh networks.

I'd very much like to be able to run two masters; one for my live sensor network, and one for my development network.

Is something like this even possible?

**Comment by TMRh20** [comment]
Easiest is Call mesh.begin(<channel>); and run networks on different
channels.

Sent from my iPod

On 2016-05-27, at 6:36 AM, Jan Fredrik Leversund <notifications@github.com>
wrote:

Greetings!

Have you given any thought to authenticating nodes before they're allowed
to enter into a mesh network?

I'm not primarily thinking about the security aspect of this, but rather
about how to avoid nodes hopping between two adjacent mesh networks.

I'd very much like to be able to run two masters; one for my live sensor
network, and one for my development network.

Is something like this even possible?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/TMRh20/RF24Mesh/issues/81>, or mute the thread
<https://github.com/notifications/unsubscribe/ACfVHJzmaasKQtOYt3hz8HiarvL-nW60ks5qFuVQgaJpZM4IodZ8>
.
