### ISSUE TITLE
Is there a way to refresh the list of connected nodes?

### ISSUE THREAD

**Issue by smiron** [TMRh20/RF24Mesh#83]
When using the master-slave configuration, in case a slave goes down, is there any way the master will realize this and remove the node from the addresses list?

In my scenario I have 1 Master and many slave nodes that can iterate very fast between online and offline. Ideally the master should automatically remove the dead nodes from its addresses list.

In case there isn't an automatic way of doing this, is it feasible to implement my own mechanism? What would be the correct method to remove a known node from the addresses list?

Thank you

**Comment by TMRh20** [comment]
Depending on how fast the nodes are going up/down and how many, it might
pose a problem due to the increased traffic. RF24Mesh is focused mostly on
simplicity and automated networking & management than high
performance/demanding applications.

I couldn't come up with a good universal way to manage nodes automatically,
so it is left up to users.

The easiest way is with timing, if you know approx. how often each node is
expected to send data, the master can remove them either after  a specified
period having received no data or when data received by master.

Use the setAddress
<http://tmrh20.github.io/RF24Mesh/classRF24Mesh.html#a6aafd9dbdd198487de392f9992218f04>
function
to set the network address to 0 for a given nodeID. The only catch is that
one needs to ensure that the master is not sending to nodes with a 0
address.

Nodes can also release their addresses as soon as data is sent. One problem
here is if a node sends data, confirms it, then immediately releases the
address. In this case, the master may process the data after the address is
released, and won't find the node in its list. The best workaround here is
for the node to include its nodeID in the payload.
